# 6.1 WH Data Profile

### This script contains the following:
#### 1. Importing Libraries and Data
#### 2. Data Cleaning
#### 3. Data Wrangling
#### 4. Data Merge
#### 5. Exporting Data

### 1. Importing Libraries and Data

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
# Define path

path = r'/Users/giadairene/Documents/CareerFoundry Data Analytics/Data Analytics Immersion/Achievement 6/World_Happiness_Analysis'

In [3]:
# Import data

df_2019 = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'World Happiness Report 2019.csv'), index_col = False)

df_2020 = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'World Happiness Report 2020.csv'), index_col = False)

df_2021 = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'World Happiness Report 2021.csv'), index_col = False)

df_2022 = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'World Happiness Report 2022.csv'), index_col = False)

df_2023 = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'World Happiness Report 2023.csv'), index_col = False)

### 2. Data Cleaning

#### Exploring Datasets:

In [4]:
# Check dataset shape

df_2019.shape

(156, 9)

In [9]:
df_2019.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [11]:
df_2019.dtypes

Overall rank                      int64
Country or region                object
Score                           float64
GDP per capita                  float64
Social support                  float64
Healthy life expectancy         float64
Freedom to make life choices    float64
Generosity                      float64
Perceptions of corruption       float64
dtype: object

In [10]:
df_2019.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [12]:
# Check dataset shape

df_2020.shape

(153, 20)

In [13]:
df_2020.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [14]:
df_2020.dtypes

Country name                                   object
Regional indicator                             object
Ladder score                                  float64
Standard error of ladder score                float64
upperwhisker                                  float64
lowerwhisker                                  float64
Logged GDP per capita                         float64
Social support                                float64
Healthy life expectancy                       float64
Freedom to make life choices                  float64
Generosity                                    float64
Perceptions of corruption                     float64
Ladder score in Dystopia                      float64
Explained by: Log GDP per capita              float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Dystopia + residual                           float64
dtype: object

In [15]:
df_2020.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [16]:
# Check dataset shape

df_2021.shape

(149, 20)

In [17]:
df_2021.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [18]:
df_2021.dtypes

Country name                                   object
Regional indicator                             object
Ladder score                                  float64
Standard error of ladder score                float64
upperwhisker                                  float64
lowerwhisker                                  float64
Logged GDP per capita                         float64
Social support                                float64
Healthy life expectancy                       float64
Freedom to make life choices                  float64
Generosity                                    float64
Perceptions of corruption                     float64
Ladder score in Dystopia                      float64
Explained by: Log GDP per capita              float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Dystopia + residual                           float64
dtype: object

In [19]:
df_2021.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [7]:
# Check dataset shape

df_2022.shape

(146, 12)

In [20]:
df_2022.columns

Index(['RANK', 'Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Dystopia (1.83) + residual', 'Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')

In [21]:
df_2022.dtypes

RANK                                            int64
Country                                        object
Happiness score                               float64
Whisker-high                                  float64
Whisker-low                                   float64
Dystopia (1.83) + residual                    float64
Explained by: GDP per capita                  float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
dtype: object

In [22]:
df_2022.head()

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,7.821,7.886,7.756,2.518,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,7.636,7.710,7.563,2.226,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,7.557,7.651,7.464,2.320,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,7.512,7.586,7.437,2.153,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,7.415,7.471,7.359,2.137,1.945,1.206,0.787,0.651,0.271,0.419

In [8]:
# Check dataset shape

df_2023.shape

(137, 19)

In [23]:
df_2023.columns

Index(['Country name', 'Ladder score', 'Standard error of ladder score',
       'upperwhisker', 'lowerwhisker', 'Logged GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [24]:
df_2023.dtypes

Country name                                   object
Ladder score                                  float64
Standard error of ladder score                float64
upperwhisker                                  float64
lowerwhisker                                  float64
Logged GDP per capita                         float64
Social support                                float64
Healthy life expectancy                       float64
Freedom to make life choices                  float64
Generosity                                    float64
Perceptions of corruption                     float64
Ladder score in Dystopia                      float64
Explained by: Log GDP per capita              float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Dystopia + residual                           float64
dtype: object

In [25]:
df_2023.head()

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.804,0.036,7.875,7.733,10.792,0.969,71.150,0.961,-0.019,0.182,1.778,1.888,1.585,0.535,0.772,0.126,0.535,2.363
1,Denmark,7.586,0.041,7.667,7.506,10.962,0.954,71.250,0.934,0.134,0.196,1.778,1.949,1.548,0.537,0.734,0.208,0.525,2.084
2,Iceland,7.530,0.049,7.625,7.434,10.896,0.983,72.050,0.936,0.211,0.668,1.778,1.926,1.620,0.559,0.738,0.250,0.187,2.250
3,Israel,7.473,0.032,7.535,7.411,10.639,0.943,72.697,0.809,-0.023,0.708,1.778,1.833,1.521,0.577,0.569,0.124,0.158,2.691
4,Netherlands,7.403,0.029,7.460,7.346,10.942,0.930,71.550,0.887,0.213,0.379,1.778,1.942,1.488,0.545,0.672,0.251,0.394,2.110

#### Missing Values Check:

In [26]:
# Check for missing values

df_2019.isnull().sum() # No missing values!

Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [27]:
# Check for missing values

df_2020.isnull().sum() # No missing values!

Country name                                  0
Regional indicator                            0
Ladder score                                  0
Standard error of ladder score                0
upperwhisker                                  0
lowerwhisker                                  0
Logged GDP per capita                         0
Social support                                0
Healthy life expectancy                       0
Freedom to make life choices                  0
Generosity                                    0
Perceptions of corruption                     0
Ladder score in Dystopia                      0
Explained by: Log GDP per capita              0
Explained by: Social support                  0
Explained by: Healthy life expectancy         0
Explained by: Freedom to make life choices    0
Explained by: Generosity                      0
Explained by: Perceptions of corruption       0
Dystopia + residual                           0
dtype: int64

In [28]:
# Check for missing values

df_2021.isnull().sum() # No missing values!

Country name                                  0
Regional indicator                            0
Ladder score                                  0
Standard error of ladder score                0
upperwhisker                                  0
lowerwhisker                                  0
Logged GDP per capita                         0
Social support                                0
Healthy life expectancy                       0
Freedom to make life choices                  0
Generosity                                    0
Perceptions of corruption                     0
Ladder score in Dystopia                      0
Explained by: Log GDP per capita              0
Explained by: Social support                  0
Explained by: Healthy life expectancy         0
Explained by: Freedom to make life choices    0
Explained by: Generosity                      0
Explained by: Perceptions of corruption       0
Dystopia + residual                           0
dtype: int64

In [29]:
# Check for missing values

df_2022.isnull().sum() # No missing values!

RANK                                          0
Country                                       0
Happiness score                               0
Whisker-high                                  0
Whisker-low                                   0
Dystopia (1.83) + residual                    0
Explained by: GDP per capita                  0
Explained by: Social support                  0
Explained by: Healthy life expectancy         0
Explained by: Freedom to make life choices    0
Explained by: Generosity                      0
Explained by: Perceptions of corruption       0
dtype: int64

In [30]:
# Check for missing values

df_2023.isnull().sum() # 3 missing values

Country name                                  0
Ladder score                                  0
Standard error of ladder score                0
upperwhisker                                  0
lowerwhisker                                  0
Logged GDP per capita                         0
Social support                                0
Healthy life expectancy                       1
Freedom to make life choices                  0
Generosity                                    0
Perceptions of corruption                     0
Ladder score in Dystopia                      0
Explained by: Log GDP per capita              0
Explained by: Social support                  0
Explained by: Healthy life expectancy         1
Explained by: Freedom to make life choices    0
Explained by: Generosity                      0
Explained by: Perceptions of corruption       0
Dystopia + residual                           1
dtype: int64

#### Duplicates Check:

In [31]:
# Find duplicates

df_dups = df_2019[df_2019.duplicated()]

In [32]:
df_dups.shape # No duplicates!

(0, 9)

In [33]:
# Find duplicates

df_dups = df_2020[df_2020.duplicated()]

In [34]:
df_dups.shape # No duplicates!

(0, 20)

In [35]:
# Find duplicates

df_dups = df_2021[df_2021.duplicated()]

In [36]:
df_dups.shape # No duplicates!

(0, 20)

In [37]:
# Find duplicates

df_dups = df_2022[df_2022.duplicated()]

In [38]:
df_dups.shape # No duplicates!

(0, 12)

In [39]:
# Find duplicates

df_dups = df_2023[df_2023.duplicated()]

In [40]:
df_dups.shape # No duplicates!

(0, 19)

#### Mixed-Type Data:

In [42]:
for col in df_2019.columns.tolist():
      weird = (df_2019[[col]].map(type) != df_2019[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df_2019[weird]) > 0:
        print (col)
        
# No mixed-type columns either!

In [43]:
for col in df_2020.columns.tolist():
      weird = (df_2020[[col]].map(type) != df_2020[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df_2020[weird]) > 0:
        print (col)
        
# No mixed-type columns either!

In [44]:
for col in df_2021.columns.tolist():
      weird = (df_2021[[col]].map(type) != df_2021[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df_2021[weird]) > 0:
        print (col)
        
# No mixed-type columns either!

In [45]:
for col in df_2022.columns.tolist():
      weird = (df_2022[[col]].map(type) != df_2022[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df_2022[weird]) > 0:
        print (col)
        
# No mixed-type columns either!

In [46]:
for col in df_2023.columns.tolist():
      weird = (df_2023[[col]].map(type) != df_2023[[col]].iloc[0].apply(type)).any(axis = 1)
      if len (df_2023[weird]) > 0:
        print (col)
        
# No mixed-type columns either!

#### Descriptive Statistics:

In [48]:
df_2019.describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,5.407096,0.905147,1.208814,0.725244,0.392571,0.184846,0.110603
std,45.177428,1.113120,0.398389,0.299191,0.242124,0.143289,0.095254,0.094538
min,1.000000,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.544500,0.602750,1.055750,0.547750,0.308000,0.108750,0.047000
50%,78.500000,5.379500,0.960000,1.271500,0.789000,0.417000,0.177500,0.085500
75%,117.250000,6.184500,1.232500,1.452500,0.881750,0.507250,0.248250,0.141250
max,156.000000,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000

In [49]:
df_2020.describe()

,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
count,153.00000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,1.530000e+02,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000,153.000000
mean,5.47324,0.053538,5.578175,5.368304,9.295706,0.808721,64.445529,0.783360,-0.014568,0.733120,1.972317e+00,0.868771,1.155607,0.692869,0.463583,0.189375,0.130718,1.972317
std,1.11227,0.018183,1.096823,1.128631,1.201588,0.121453,7.057848,0.117786,0.151809,0.175172,1.559417e-15,0.372416,0.286866,0.254094,0.141172,0.100401,0.113097,0.563638
min,2.56690,0.025902,2.628270,2.505530,6.492642,0.319460,45.200001,0.396573,-0.300907,0.109784,1.972317e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.257241
25%,4.72410,0.040698,4.826248,4.603149,8.350645,0.737217,58.961712,0.714839,-0.127015,0.683019,1.972317e+00,0.575862,0.986718,0.495443,0.381457,0.115006,0.055805,1.629928
50%,5.51500,0.050606,5.607728,5.430644,9.456313,0.829204,66.305145,0.799805,-0.033665,0.783122,1.972317e+00,0.918549,1.203987,0.759818,0.483293,0.176745,0.098435,2.046272
75%,6.22850,0.060677,6.363886,6.138881,10.265124,0.906747,69.289192,0.877709,0.085429,0.849151,1.972317e+00,1.169229,1.387139,0.867249,0.576665,0.255510,0.163064,2.350267
max,7.80870,0.120590,7.869766,7.747634,11.450681,0.974670,76.804581,0.974998,0.560664,0.935585,1.972317e+00,1.536676,1.547567,1.137814,0.693270,0.569814,0.533162,3.440810

In [50]:
df_2021.describe()

,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
count,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,1.490000e+02,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000
mean,5.532839,0.058752,5.648007,5.417631,9.432208,0.814745,64.992799,0.791597,-0.015134,0.727450,2.430000e+00,0.977161,0.793315,0.520161,0.498711,0.178047,0.135141,2.430329
std,1.073924,0.022001,1.054330,1.094879,1.158601,0.114889,6.762043,0.113332,0.150657,0.179226,5.347044e-15,0.404740,0.258871,0.213019,0.137888,0.098270,0.114361,0.537645
min,2.523000,0.026000,2.596000,2.449000,6.635000,0.463000,48.478000,0.382000,-0.288000,0.082000,2.430000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.648000
25%,4.852000,0.043000,4.991000,4.706000,8.541000,0.750000,59.802000,0.718000,-0.126000,0.667000,2.430000e+00,0.666000,0.647000,0.357000,0.409000,0.105000,0.060000,2.138000
50%,5.534000,0.054000,5.625000,5.413000,9.569000,0.832000,66.603000,0.804000,-0.036000,0.781000,2.430000e+00,1.025000,0.832000,0.571000,0.514000,0.164000,0.101000,2.509000
75%,6.255000,0.070000,6.344000,6.128000,10.421000,0.905000,69.600000,0.877000,0.079000,0.845000,2.430000e+00,1.323000,0.996000,0.665000,0.603000,0.239000,0.174000,2.794000
max,7.842000,0.173000,7.904000,7.780000,11.647000,0.983000,76.953000,0.970000,0.542000,0.939000,2.430000e+00,1.751000,1.172000,0.897000,0.716000,0.541000,0.547000,3.482000

In [51]:
df_2022.describe()

,RANK,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
count,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000,146.000000
mean,73.500000,5.553575,5.673589,5.433568,1.831808,1.410445,0.905863,0.586171,0.517226,0.147377,0.154781
std,42.290661,1.086843,1.065621,1.109380,0.534994,0.421663,0.280122,0.176336,0.145859,0.082799,0.127514
min,1.000000,2.404000,2.469000,2.339000,0.187000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37.250000,4.888750,5.006250,4.754750,1.555250,1.095500,0.732000,0.463250,0.440500,0.089000,0.068250
50%,73.500000,5.568500,5.680000,5.453000,1.894500,1.445500,0.957500,0.621500,0.543500,0.132500,0.119500
75%,109.750000,6.305000,6.448750,6.190000,2.153000,1.784750,1.114250,0.719750,0.626000,0.197750,0.198500
max,146.000000,7.821000,7.886000,7.756000,2.844000,2.209000,1.320000,0.942000,0.740000,0.468000,0.587000

In [52]:
df_2023.describe()

,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
count,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000,136.000000,137.000000,137.000000,137.000000,1.370000e+02,137.000000,137.000000,136.000000,137.000000,137.000000,137.000000,136.000000
mean,5.539796,0.064715,5.666526,5.412971,9.449796,0.799073,64.967632,0.787394,0.022431,0.725401,1.778000e+00,1.406985,1.156212,0.366176,0.540000,0.148474,0.145898,1.777838
std,1.139929,0.023031,1.117421,1.163724,1.207302,0.129222,5.750390,0.112371,0.141707,0.176956,2.897173e-15,0.432963,0.326322,0.156691,0.149501,0.076053,0.126723,0.504390
min,1.859000,0.029000,1.923000,1.795000,5.527000,0.341000,51.530000,0.382000,-0.254000,0.146000,1.778000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.110000
25%,4.724000,0.047000,4.980000,4.496000,8.591000,0.722000,60.648500,0.724000,-0.074000,0.668000,1.778000e+00,1.099000,0.962000,0.248500,0.455000,0.097000,0.060000,1.555250
50%,5.684000,0.060000,5.797000,5.529000,9.567000,0.827000,65.837500,0.801000,0.001000,0.774000,1.778000e+00,1.449000,1.227000,0.389500,0.557000,0.137000,0.111000,1.848500
75%,6.334000,0.077000,6.441000,6.243000,10.540000,0.896000,69.412500,0.874000,0.117000,0.846000,1.778000e+00,1.798000,1.401000,0.487500,0.656000,0.199000,0.187000,2.078750
max,7.804000,0.147000,7.875000,7.733000,11.660000,0.983000,77.280000,0.961000,0.531000,0.929000,1.778000e+00,2.200000,1.620000,0.702000,0.772000,0.422000,0.561000,2.955000

### 3. Data Wrangling

#### Dropping Columns:

In [53]:
# Check columns

df_2020.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [54]:
# Drop unnecessary or not-in-common columns

df_2020 = df_2020.drop(columns=['Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
                                'Logged GDP per capita', 'Social support', 'Healthy life expectancy', 
                                'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 
                                'Ladder score in Dystopia', 'Dystopia + residual'])

In [55]:
# Check the output

df_2020.head()

,Country name,Regional indicator,Ladder score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,Western Europe,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857
1,Denmark,Western Europe,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260
2,Switzerland,Western Europe,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946
3,Iceland,Western Europe,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541
4,Norway,Western Europe,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101

In [56]:
# Check columns

df_2021.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [57]:
# Drop unnecessary or not-in-common columns

df_2021 = df_2021.drop(columns=['Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
                                'Logged GDP per capita', 'Social support', 'Healthy life expectancy', 
                                'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 
                                'Ladder score in Dystopia', 'Dystopia + residual'])

In [58]:
# Check the output

df_2021.head()

,Country name,Regional indicator,Ladder score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,Western Europe,7.842,1.446,1.106,0.741,0.691,0.124,0.481
1,Denmark,Western Europe,7.620,1.502,1.108,0.763,0.686,0.208,0.485
2,Switzerland,Western Europe,7.571,1.566,1.079,0.816,0.653,0.204,0.413
3,Iceland,Western Europe,7.554,1.482,1.172,0.772,0.698,0.293,0.170
4,Netherlands,Western Europe,7.464,1.501,1.079,0.753,0.647,0.302,0.384

In [59]:
# Check columns

df_2022.columns

Index(['RANK', 'Country', 'Happiness score', 'Whisker-high', 'Whisker-low',
       'Dystopia (1.83) + residual', 'Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')

In [60]:
# Drop unnecessary or not-in-common columns

df_2022 = df_2022.drop(columns=['Whisker-high', 'Whisker-low', 'Dystopia (1.83) + residual'])

In [61]:
# Check the output

df_2022.head()

,RANK,Country,Happiness score,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,7.821,1.892,1.258,0.775,0.736,0.109,0.534
1,2,Denmark,7.636,1.953,1.243,0.777,0.719,0.188,0.532
2,3,Iceland,7.557,1.936,1.320,0.803,0.718,0.270,0.191
3,4,Switzerland,7.512,2.026,1.226,0.822,0.677,0.147,0.461
4,5,Netherlands,7.415,1.945,1.206,0.787,0.651,0.271,0.419

In [62]:
# Check columns

df_2023.columns

Index(['Country name', 'Ladder score', 'Standard error of ladder score',
       'upperwhisker', 'lowerwhisker', 'Logged GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [63]:
# Drop unnecessary or not-in-common columns

df_2023 = df_2023.drop(columns=['Standard error of ladder score', 'upperwhisker', 'lowerwhisker', 
                                'Logged GDP per capita', 'Social support', 'Healthy life expectancy', 
                                'Freedom to make life choices', 'Generosity','Perceptions of corruption', 
                                'Ladder score in Dystopia', 'Dystopia + residual'])

In [64]:
# Check the output

df_2023.head()

,Country name,Ladder score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.804,1.888,1.585,0.535,0.772,0.126,0.535
1,Denmark,7.586,1.949,1.548,0.537,0.734,0.208,0.525
2,Iceland,7.530,1.926,1.620,0.559,0.738,0.250,0.187
3,Israel,7.473,1.833,1.521,0.577,0.569,0.124,0.158
4,Netherlands,7.403,1.942,1.488,0.545,0.672,0.251,0.394

#### Renaming and Adding Columns:

In [65]:
# Check columns

df_2019.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [66]:
# Rename columns

df_2019.rename(columns = {'Overall rank' : 'Happiness_rank'}, inplace = True)

df_2019.rename(columns = {'Country or region' : 'Country'}, inplace = True)

df_2019.rename(columns = {'Score' : 'Happiness_score'}, inplace = True)

df_2019.rename(columns = {'GDP per capita' : 'GDP_capita'}, inplace = True)

df_2019.rename(columns = {'Social support' : 'Social_support'}, inplace = True)

df_2019.rename(columns = {'Healthy life expectancy' : 'Life_expectancy'}, inplace = True)

df_2019.rename(columns = {'Freedom to make life choices' : 'Freedom'}, inplace = True)

df_2019.rename(columns = {'Perceptions of corruption' : 'Corruption_perception'}, inplace = True)

In [67]:
# Assign column names in a specific order

df_2019 = df_2019[['Country', 'Happiness_rank', 'Happiness_score', 'GDP_capita', 'Social_support', 'Life_expectancy', 'Freedom', 'Generosity', 'Corruption_perception']]

In [79]:
# Add 'Year' column

df_2019.insert(1, 'Year', '2019')

ValueError: cannot insert Year, already exists

In [80]:
# Check output

df_2019

,Country,Year,Happiness_rank,Happiness_score,GDP_capita,Social_support,Life_expectancy,Freedom,Generosity,Corruption_perception
0,Finland,2019,1,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,2019,2,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,2019,3,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,2019,4,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,2019,5,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,2019,152,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,Tanzania,2019,153,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,Afghanistan,2019,154,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,Central African Republic,2019,155,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,South Sudan,2019,156,2.853,0.306,0.575,0.295,0.010,0.202,0.091

In [70]:
# Check columns

df_2020.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')

In [71]:
# Rename columns

df_2020.rename(columns = {'Regional indicator' : 'Region'}, inplace = True)

df_2020.rename(columns = {'Country name' : 'Country'}, inplace = True)

df_2020.rename(columns = {'Ladder score' : 'Happiness_score'}, inplace = True)

df_2020.rename(columns = {'Explained by: Log GDP per capita' : 'GDP_capita'}, inplace = True)

df_2020.rename(columns = {'Explained by: Social support' : 'Social_support'}, inplace = True)

df_2020.rename(columns = {'Explained by: Healthy life expectancy' : 'Life_expectancy'}, inplace = True)

df_2020.rename(columns = {'Explained by: Freedom to make life choices' : 'Freedom'}, inplace = True)

df_2020.rename(columns = {'Explained by: Generosity' : 'Generosity'}, inplace = True)

df_2020.rename(columns = {'Explained by: Perceptions of corruption' : 'Corruption_perception'}, inplace = True)

In [73]:
# Assign column names in a specific order

df_2020 = df_2020[['Country', 'Region', 'Happiness_score', 'GDP_capita', 'Social_support', 'Life_expectancy', 'Freedom', 'Generosity', 'Corruption_perception']]

In [81]:
# Add 'Year' column

df_2020.insert(2, 'Year', '2020')

In [82]:
# Check output

df_2020

,Country,Region,Year,Happiness_score,GDP_capita,Social_support,Life_expectancy,Freedom,Generosity,Corruption_perception
0,Finland,Western Europe,2020,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857
1,Denmark,Western Europe,2020,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260
2,Switzerland,Western Europe,2020,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946
3,Iceland,Western Europe,2020,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541
4,Norway,Western Europe,2020,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101
...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,2020,3.4759,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265
149,Rwanda,Sub-Saharan Africa,2020,3.3123,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542
150,Zimbabwe,Sub-Saharan Africa,2020,3.2992,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929
151,South Sudan,Sub-Saharan Africa,2020,2.8166,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157
152,Afghanistan,South Asia,2020,2.5669,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226

In [83]:
# Check columns

df_2021.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')

In [84]:
# Rename columns

df_2021.rename(columns = {'Regional indicator' : 'Region'}, inplace = True)

df_2021.rename(columns = {'Country name' : 'Country'}, inplace = True)

df_2021.rename(columns = {'Ladder score' : 'Happiness_score'}, inplace = True)

df_2021.rename(columns = {'Explained by: Log GDP per capita' : 'GDP_capita'}, inplace = True)

df_2021.rename(columns = {'Explained by: Social support' : 'Social_support'}, inplace = True)

df_2021.rename(columns = {'Explained by: Healthy life expectancy' : 'Life_expectancy'}, inplace = True)

df_2021.rename(columns = {'Explained by: Freedom to make life choices' : 'Freedom'}, inplace = True)

df_2021.rename(columns = {'Explained by: Generosity' : 'Generosity'}, inplace = True)

df_2021.rename(columns = {'Explained by: Perceptions of corruption' : 'Corruption_perception'}, inplace = True)

In [85]:
# Assign column names in a specific order

df_2021 = df_2021[['Country', 'Region', 'Happiness_score', 'GDP_capita', 'Social_support', 'Life_expectancy', 'Freedom', 'Generosity', 'Corruption_perception']]

In [87]:
# Add 'Year' column

df_2021.insert(2, 'Year', '2021')

In [95]:
# Check output

df_2021

,Country,Region,Year,Happiness_score,GDP_capita,Social_support,Life_expectancy,Freedom,Generosity,Corruption_perception
0,Finland,Western Europe,2021,7.842,1.446,1.106,0.741,0.691,0.124,0.481
1,Denmark,Western Europe,2021,7.620,1.502,1.108,0.763,0.686,0.208,0.485
2,Switzerland,Western Europe,2021,7.571,1.566,1.079,0.816,0.653,0.204,0.413
3,Iceland,Western Europe,2021,7.554,1.482,1.172,0.772,0.698,0.293,0.170
4,Netherlands,Western Europe,2021,7.464,1.501,1.079,0.753,0.647,0.302,0.384
...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,2021,3.512,0.451,0.731,0.007,0.405,0.103,0.015
145,Botswana,Sub-Saharan Africa,2021,3.467,1.099,0.724,0.340,0.539,0.027,0.088
146,Rwanda,Sub-Saharan Africa,2021,3.415,0.364,0.202,0.407,0.627,0.227,0.493
147,Zimbabwe,Sub-Saharan Africa,2021,3.145,0.457,0.649,0.243,0.359,0.157,0.075
148,Afghanistan,South Asia,2021,2.523,0.370,0.000,0.126,0.000,0.122,0.010

In [89]:
# Check columns

df_2022.columns

Index(['RANK', 'Country', 'Happiness score', 'Explained by: GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')

In [90]:
# Rename columns

df_2022.rename(columns = {'RANK' : 'Happiness_rank'}, inplace = True)

df_2022.rename(columns = {'Country' : 'Country'}, inplace = True)

df_2022.rename(columns = {'Happiness score' : 'Happiness_score'}, inplace = True)

df_2022.rename(columns = {'Explained by: GDP per capita' : 'GDP_capita'}, inplace = True)

df_2022.rename(columns = {'Explained by: Social support' : 'Social_support'}, inplace = True)

df_2022.rename(columns = {'Explained by: Healthy life expectancy' : 'Life_expectancy'}, inplace = True)

df_2022.rename(columns = {'Explained by: Freedom to make life choices' : 'Freedom'}, inplace = True)

df_2022.rename(columns = {'Explained by: Generosity' : 'Generosity'}, inplace = True)

df_2022.rename(columns = {'Explained by: Perceptions of corruption' : 'Corruption_perception'}, inplace = True)

In [91]:
# Assign column names in a specific order

df_2022 = df_2022[['Country', 'Happiness_rank', 'Happiness_score', 'GDP_capita', 'Social_support', 'Life_expectancy', 'Freedom', 'Generosity', 'Corruption_perception']]

In [93]:
# Add 'Year' column

df_2022.insert(1, 'Year', '2022')

In [94]:
# Check output

df_2022

,Country,Year,Happiness_rank,Happiness_score,GDP_capita,Social_support,Life_expectancy,Freedom,Generosity,Corruption_perception
0,Finland,2022,1,7.821,1.892,1.258,0.775,0.736,0.109,0.534
1,Denmark,2022,2,7.636,1.953,1.243,0.777,0.719,0.188,0.532
2,Iceland,2022,3,7.557,1.936,1.320,0.803,0.718,0.270,0.191
3,Switzerland,2022,4,7.512,2.026,1.226,0.822,0.677,0.147,0.461
4,Netherlands,2022,5,7.415,1.945,1.206,0.787,0.651,0.271,0.419
...,...,...,...,...,...,...,...,...,...,...
141,Botswana*,2022,142,3.471,1.503,0.815,0.280,0.571,0.012,0.102
142,Rwanda*,2022,143,3.268,0.785,0.133,0.462,0.621,0.187,0.544
143,Zimbabwe,2022,144,2.995,0.947,0.690,0.270,0.329,0.106,0.105
144,Lebanon,2022,145,2.955,1.392,0.498,0.631,0.103,0.082,0.034
145,Afghanistan,2022,146,2.404,0.758,0.000,0.289,0.000,0.089,0.005

In [96]:
# Check columns

df_2023.columns

Index(['Country name', 'Ladder score', 'Explained by: Log GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption'],
      dtype='object')

In [97]:
# Rename columns

df_2023.rename(columns = {'Country name' : 'Country'}, inplace = True)

df_2023.rename(columns = {'Ladder score' : 'Happiness_score'}, inplace = True)

df_2023.rename(columns = {'Explained by: Log GDP per capita' : 'GDP_capita'}, inplace = True)

df_2023.rename(columns = {'Explained by: Social support' : 'Social_support'}, inplace = True)

df_2023.rename(columns = {'Explained by: Healthy life expectancy' : 'Life_expectancy'}, inplace = True)

df_2023.rename(columns = {'Explained by: Freedom to make life choices' : 'Freedom'}, inplace = True)

df_2023.rename(columns = {'Explained by: Generosity' : 'Generosity'}, inplace = True)

df_2023.rename(columns = {'Explained by: Perceptions of corruption' : 'Corruption_perception'}, inplace = True)

In [98]:
# Assign column names in a specific order

df_2023 = df_2023[['Country', 'Happiness_score', 'GDP_capita', 'Social_support', 'Life_expectancy', 'Freedom', 'Generosity', 'Corruption_perception']]

In [99]:
# Add 'Year' column

df_2023.insert(1, 'Year', '2023')

In [100]:
# Check output

df_2023

,Country,Year,Happiness_score,GDP_capita,Social_support,Life_expectancy,Freedom,Generosity,Corruption_perception
0,Finland,2023,7.804,1.888,1.585,0.535,0.772,0.126,0.535
1,Denmark,2023,7.586,1.949,1.548,0.537,0.734,0.208,0.525
2,Iceland,2023,7.530,1.926,1.620,0.559,0.738,0.250,0.187
3,Israel,2023,7.473,1.833,1.521,0.577,0.569,0.124,0.158
4,Netherlands,2023,7.403,1.942,1.488,0.545,0.672,0.251,0.394
...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),2023,3.207,0.531,0.784,0.105,0.375,0.183,0.068
133,Zimbabwe,2023,3.204,0.758,0.881,0.069,0.363,0.112,0.117
134,Sierra Leone,2023,3.138,0.670,0.540,0.092,0.371,0.193,0.051
135,Lebanon,2023,2.392,1.417,0.476,0.398,0.123,0.061,0.027
136,Afghanistan,2023,1.859,0.645,0.000,0.087,0.000,0.093,0.059

### 4. Data Merge

In [101]:
# Concatenate the dataframes along the rows

combined_df = pd.concat([df_2019, df_2020, df_2021, df_2022, df_2023])

In [102]:
# Check output

combined_df

,Country,Year,Happiness_rank,Happiness_score,GDP_capita,Social_support,Life_expectancy,Freedom,Generosity,Corruption_perception,Region
0,Finland,2019,1.0,7.769,1.340,1.587,0.986,0.596,0.153,0.393,NaN
1,Denmark,2019,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410,NaN
2,Norway,2019,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341,NaN
3,Iceland,2019,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118,NaN
4,Netherlands,2019,5.0,7.488,1.396,1.522,0.999,0.557,0.322,0.298,NaN
...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),2023,NaN,3.207,0.531,0.784,0.105,0.375,0.183,0.068,NaN
133,Zimbabwe,2023,NaN,3.204,0.758,0.881,0.069,0.363,0.112,0.117,NaN
134,Sierra Leone,2023,NaN,3.138,0.670,0.540,0.092,0.371,0.193,0.051,NaN
135,Lebanon,2023,NaN,2.392,1.417,0.476,0.398,0.123,0.061,0.027,NaN
136,Afghanistan,2023,NaN,1.859,0.645,0.000,0.087,0.000,0.093,0.059,NaN

In [103]:
# Assign column names in a specific order

combined_df = combined_df[['Country', 'Region', 'Year', 'Happiness_rank', 'Happiness_score', 'GDP_capita', 'Social_support', 'Life_expectancy', 'Freedom', 'Generosity', 'Corruption_perception']]

In [104]:
# Check output

combined_df

,Country,Region,Year,Happiness_rank,Happiness_score,GDP_capita,Social_support,Life_expectancy,Freedom,Generosity,Corruption_perception
0,Finland,NaN,2019,1.0,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,NaN,2019,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,NaN,2019,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,NaN,2019,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,NaN,2019,5.0,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),NaN,2023,NaN,3.207,0.531,0.784,0.105,0.375,0.183,0.068
133,Zimbabwe,NaN,2023,NaN,3.204,0.758,0.881,0.069,0.363,0.112,0.117
134,Sierra Leone,NaN,2023,NaN,3.138,0.670,0.540,0.092,0.371,0.193,0.051
135,Lebanon,NaN,2023,NaN,2.392,1.417,0.476,0.398,0.123,0.061,0.027
136,Afghanistan,NaN,2023,NaN,1.859,0.645,0.000,0.087,0.000,0.093,0.059

In [105]:
# Reset the index

combined_df.reset_index(drop=True, inplace=True)

In [106]:
combined_df

,Country,Region,Year,Happiness_rank,Happiness_score,GDP_capita,Social_support,Life_expectancy,Freedom,Generosity,Corruption_perception
0,Finland,NaN,2019,1.0,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,NaN,2019,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,NaN,2019,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,NaN,2019,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,NaN,2019,5.0,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...,...,...
736,Congo (Kinshasa),NaN,2023,NaN,3.207,0.531,0.784,0.105,0.375,0.183,0.068
737,Zimbabwe,NaN,2023,NaN,3.204,0.758,0.881,0.069,0.363,0.112,0.117
738,Sierra Leone,NaN,2023,NaN,3.138,0.670,0.540,0.092,0.371,0.193,0.051
739,Lebanon,NaN,2023,NaN,2.392,1.417,0.476,0.398,0.123,0.061,0.027
740,Afghanistan,NaN,2023,NaN,1.859,0.645,0.000,0.087,0.000,0.093,0.059

### 5. Exporting data

In [107]:
# Export each wrangled dataset

df_2019.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'df_2019_wrangled.csv'))

df_2020.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'df_2020_wrangled.csv'))

df_2021.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'df_2021_wrangled.csv'))

df_2022.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'df_2022_wrangled.csv'))

df_2023.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'df_2023_wrangled.csv'))

In [108]:
# Export the combined dataset

combined_df.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'Happiness_combined_all_years.csv'))